# Generated by Django 5.0.2 on 2024-02-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(blank=True, max_length=16)),
                ('password', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
