# Generated by Django 5.0.2 on 2024-02-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_customers_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
