# Generated by Django 5.0.2 on 2024-02-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
