# Generated by Django 5.0.2 on 2024-02-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_remove_brand_slug_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brd_slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
