# Generated by Django 5.0.2 on 2024-02-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_brand_brd_slug_category_cat_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brd_slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_slug',
        ),
    ]
