# Generated by Django 5.0.2 on 2024-02-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='variant_slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
