# Generated by Django 5.0.2 on 2024-03-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='offer',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
