# Generated by Django 5.0.2 on 2024-03-04 20:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "checkout",
            "0003_remove_order_address_address_order_billing_address_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="billing_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
