# Generated by Django 5.0.2 on 2024-03-20 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_address2'),
        ('checkout', '0010_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('locality', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('district', models.CharField(max_length=14)),
                ('state', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.customers')),
            ],
        ),
    ]
