# Generated by Django 5.0.2 on 2024-03-20 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_remove_order_address_orderaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
        ),
    ]
