# Generated by Django 5.0.2 on 2024-03-20 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitems'),
        ('checkout', '0013_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='cart_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
