# Generated by Django 5.0.2 on 2024-03-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_order_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.CharField(default='No Coupon', max_length=15),
        ),
    ]
