# Generated by Django 5.0.2 on 2024-03-09 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_1", "0007_address2"),
        ("category", "0010_alter_brand_name"),
        ("offers", "0001_initial"),
        ("products", "0018_product_variant_rom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product_offer",
            name="product",
        ),
        migrations.RemoveField(
            model_name="referral_offer",
            name="referred_by",
        ),
        migrations.CreateModel(
            name="BrandOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_code", models.CharField(max_length=10)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "maximum_discountAmount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "minimum_discountAmount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="category.brand"
                    ),
                ),
            ],
            options={
                "db_table": "Brand_Offer",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProductOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_code", models.CharField(max_length=10)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "maximum_discountAmount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "minimum_discountAmount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
            ],
            options={
                "db_table": "Product_Offer",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ReferralOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_code", models.CharField(max_length=10)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "maximum_discountAmount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "minimum_discountAmount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                ("name", models.CharField(max_length=100)),
                ("referral_code", models.CharField(max_length=10, unique=True)),
                (
                    "referred_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="app_1.customers",
                    ),
                ),
            ],
            options={
                "db_table": "Referral_Offer",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="Brand_Offer",
        ),
        migrations.DeleteModel(
            name="Product_Offer",
        ),
        migrations.DeleteModel(
            name="Referral_Offer",
        ),
    ]
