# Generated by Django 5.0.2 on 2024-03-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0002_remove_product_offer_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referraloffer",
            name="name",
        ),
        migrations.AlterField(
            model_name="brandoffer",
            name="offer_code",
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="productoffer",
            name="offer_code",
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="referraloffer",
            name="offer_code",
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
