# Generated by Django 5.0.2 on 2024-03-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0004_alter_brandoffer_valid_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandoffer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productoffer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="referraloffer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
