# Generated by Django 5.0.2 on 2024-03-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_brandoffer_is_active_productoffer_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='referraloffer',
            options={},
        ),
        migrations.RenameField(
            model_name='referraloffer',
            old_name='discount_percentage',
            new_name='referral_amount',
        ),
        migrations.RemoveField(
            model_name='referraloffer',
            name='maximum_discountAmount',
        ),
        migrations.RemoveField(
            model_name='referraloffer',
            name='minimum_discountAmount',
        ),
        migrations.AlterField(
            model_name='referraloffer',
            name='referral_code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterModelTable(
            name='referraloffer',
            table=None,
        ),
        migrations.DeleteModel(
            name='BrandOffer',
        ),
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
