# Generated by Django 5.0.2 on 2024-03-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="stutus",
            field=models.CharField(default="Credit", max_length=10),
        ),
    ]
