# Generated by Django 5.0.2 on 2024-03-12 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_wallet_stutus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="stutus",
            new_name="transaction",
        ),
    ]
