# Generated by Django 5.0.2 on 2024-02-26 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_1', '0005_alter_customers_email_alter_customers_password'),
        ('products', '0013_alter_attribute_value_attribute_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_variant')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.customers')),
            ],
        ),
    ]
