# Generated by Django 5.0.2 on 2024-02-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_attribute_value_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='max_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='sale_price',
            field=models.IntegerField(),
        ),
    ]
