# Generated by Django 5.0.2 on 2024-02-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variant',
            name='product_variant_slug',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_slug',
        ),
    ]
