# Generated by Django 5.0.2 on 2024-02-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_variant_product_variant_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
