# Generated by Django 5.0.2 on 2024-02-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_variant_variant_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='max_price',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='sale_price',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
