# Generated by Django 5.0.2 on 2024-02-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_variant_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute_value',
            name='attribute_color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='attribute_value',
            name='attribute_ram',
            field=models.CharField(max_length=50),
        ),
    ]
