# Generated by Django 5.0.2 on 2024-03-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_alter_attribute_value_attribute_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="product_description",
        ),
        migrations.AddField(
            model_name="products",
            name="battery",
            field=models.CharField(default="Unknown", max_length=8),
        ),
        migrations.AddField(
            model_name="products",
            name="camera",
            field=models.CharField(default="Unknown", max_length=20),
        ),
        migrations.AddField(
            model_name="products",
            name="display",
            field=models.CharField(default="Unknown", max_length=10),
        ),
        migrations.AddField(
            model_name="products",
            name="processor",
            field=models.CharField(default="Unknown", max_length=20),
        ),
    ]
