# Generated by Django 5.0.2 on 2024-03-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0014_remove_products_product_description_products_battery_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product_variant",
            name="thumbnail_image1",
            field=models.ImageField(default="Unknown", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="product_variant",
            name="thumbnail_image2",
            field=models.ImageField(default="Unknown", upload_to="images/"),
        ),
    ]
