# Generated by Django 5.0.2 on 2024-03-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_product_variant_thumbnail_image1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_variant",
            name="max_price",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product_variant",
            name="sale_price",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
