# Generated by Django 5.0.2 on 2024-03-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_alter_product_variant_max_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_variant",
            name="rom",
            field=models.CharField(default="128GB", max_length=50),
        ),
    ]
