# Generated by Django 5.0.2 on 2024-03-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_variant_last_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
