# Generated by Django 5.0.2 on 2024-03-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_products_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
