# Generated by Django 5.0.2 on 2024-03-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_products_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sale_count',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
